name: Build and Publish Docker Image

# refer to https://github.com/actions/starter-workflows/blob/main/ci/docker-publish.yml

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        image_tag:
          [
            # 7-apache-buster,
            # 7.4-apache-buster,
            # 8-apache-buster,
            # 8.0-apache-buster,
            # 8.1-apache-buster,
            # 8.2-apache-buster,
            7-apache-bullseye,
            7.4-apache-bullseye,
            8-apache-bullseye,
            8.0-apache-bullseye,
            8.1-apache-bullseye,
            8.2-apache-bullseye,
            # 7-fpm-buster,
            # 7.4-fpm-buster,
            # 8-fpm-buster,
            # 8.0-fpm-buster,
            # 8.1-fpm-buster,
            # 8.2-fpm-buster,
            7-fpm-bullseye,
            7.4-fpm-bullseye,
            8-fpm-bullseye,
            8.0-fpm-bullseye,
            8.1-fpm-bullseye,
            8.2-fpm-bullseye,
          ]

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    environment: docker
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry
        # if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Prepare environment variables
        id: env
        run: |
          IMAGE_NAME=$(echo $GITHUB_REPOSITORY | sed "s#${GITHUB_REPOSITORY_OWNER}/docker-##") 
          echo "IMAGE_NAME=${IMAGE_NAME}" >> $GITHUB_OUTPUT
          TIME=$(TZ=Asia/Shanghai date +"%Y%m%d-%H%M%S")
          echo "TIME=${TIME}" >> $GITHUB_OUTPUT

      # Build and push Docker image with Buildx
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image (${{ matrix.image_tag }})
        uses: docker/build-push-action@v3
        with:
          push: true
          context: .
          build-args: VARIANT=${{ matrix.image_tag }}
          tags: |
            ${{ secrets.DOCKER_HUB_USER }}/${{ steps.env.outputs.IMAGE_NAME }}:${{ matrix.image_tag }}
            ${{ secrets.DOCKER_HUB_USER }}/${{ steps.env.outputs.IMAGE_NAME }}:${{ matrix.image_tag }}-${{ steps.env.outputs.TIME }}
