name: Build and Publish Docker Image

# refer to https://github.com/actions/starter-workflows/blob/main/ci/docker-publish.yml

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: docker.io
  # <repo>
  IMAGE_NAME: ${{ github.event.repository.name }}

jobs:
  build:
    strategy:
      matrix:
        image_tag:
          [
            7-apache-buster,
            7.4-apache-buster,
            8-apache-buster,
            8.0-apache-buster,
            8.1-apache-buster,
            8.2-apache-buster,
            7-apache-bullseye,
            7.4-apache-bullseye,
            8-apache-bullseye,
            8.0-apache-bullseye,
            8.1-apache-bullseye,
            8.2-apache-bullseye,
            7-fpm-buster,
            7.4-fpm-buster,
            8-fpm-buster,
            8.0-fpm-buster,
            8.1-fpm-buster,
            8.2-fpm-buster,
            7-fpm-bullseye,
            7.4-fpm-bullseye,
            8-fpm-bullseye,
            8.0-fpm-bullseye,
            8.1-fpm-bullseye,
            8.2-fpm-bullseye,
          ]

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    environment: docker
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        # if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Get Time
        id: time
        uses: nanzm/get-time-action@v1.1
        with:
          timeZone: 8
          format: "YYYYMMDD-HHmmss"

      # Build and push Docker image with Buildx
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image (${{ matrix.image_tag }})
        uses: docker/build-push-action@v3
        with:
          push: false
          context: .
          build-args: VARIANT=${{ matrix.image_tag }}
          tags: ${{ secrets.DOCKER_HUB_USER }}/${{ env.IMAGE_NAME }}:${{ matrix.image_tag }}, ${{ secrets.DOCKER_HUB_USER }}/${{ env.IMAGE_NAME }}:${{ matrix.image_tag }}-${{ steps.time.outputs.time }}
